name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2

      - run: sam init  
      - run: sam build --use-container -/-guided
      - run: sam deploy --config-file config/config.toml --no-confirm-changeset
